<?php

namespace Tests\Unit;

use App\Billing\FakePaymentGateway;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;
use App\User;

class BillTest extends TestCase
{
    use RefreshDatabase;
    private $paymentGateway;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->paymentGateway = new FakePaymentGateway();
    }

    /** @test  */
    public function a_bill_can_be_payed(){
        $user = factory(User::class)->create();
        $property = $user->createProperty('My property', 'property.com');
        $bill = $property->createBill('my bill', 'a good bill', 50000);

        $this->paymentGateway->pay($bill, $this->paymentGateway->getPaymentToken());

        $this->assertEquals(0, $bill->fresh()->price);
    }
}
